name: 'Terraform Destroy'

# This allows the action to be manually triggered from the GitHub Actions UI
on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest

    # Setting environment variables for Azure authentication using GitHub Secrets
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
    # Checkout the repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v2

    # Set up Terraform
    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1

    # Terraform Init
    - name: 'Terraform Init'
      run: terraform init

    # Terraform Destroy
    - name: 'Terraform Destroy'
      run: terraform destroy -auto-approve -input=false